config/routes.rb
Twitterclone::Application.routes.draw do

  root :to => "home#index"
  get "sign_in" => "sessions#new"
  resources :user do
    resources :tweet
  end
end

  

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

layout 'application'

def index
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController

#the form to create a new user
def new
	@user = User.new
end

#create user_params
def user_params
	params.require(:user).permit(:first_name, :last_name, :email, :username, :password)
end

#the POST request to submit a new user form
def create
	@user = User.create(user_params)
	if @user.save
		flash[:notice] = "Your account has been created."
	else
		flash[:notice] = "There was an error creating your account."
	end
	redirect_to root_path
end

#to edit a user
def edit
	@user = User.find(params[:id])
end

#the PUT request to update a user's information
def update
	@user = User.find(params[:id])
	if @user.update_attributes(user_params)
		flash[:notice] = "Your account was updated successfully."
	else
		flash[:notice] = "There was a problem updating your account."
	end
	redirect_to user_path(@user)
end

def show
	@user = User.find(params[:id])
end







end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
#	belongs_to :User
end

app/helpers/user_helper.rb
module UserHelper
#	has_many :Tweet
end

app/views/home/index.haml
%h3 Twitterclone

app/views/layouts/application.haml
!!!
%html
	%head
		%title Twitterclone
		= stylesheet_link_tag		"application", media: "all", "data-turbolinks-track" => true
		= stylesheet_link_tag		"flat-ui", :media => "all"
		= stylesheet_link_tag		"stylesheet", :media => "all"
		= javascript_include_tag		"application", "data-turbolinks-track" => true
		= csrf_meta_tags
	%body
		=yield

app/views/user/_form.haml
=f.label :first_name
=f.text_field :first_name
%br
=f.label :last_name
=f.text_field :last_name
%br
=f.label :username
=f.text_field :username
%br
=f.label :email
=f.text_field :email
%br
=f.label :password
=f.password_field :password
%br
=f.submit

app/views/user/edit.haml
%h1 Edit your profile

=form_for @user, :url => user_path(@user) do |f|
	=render "form", {f: f}

app/views/user/new.haml
%h1 Sign Up
=form_for User.new, :url => user_index_path do |f|
	=render "form", {f: f}

app/views/user/show.haml
%h1
	User Profile for
	=@user.first_name
%h5 
	Name:
	=@user.first_name + " " + @user.last_name
%h5
	E-mail:
	=@user.email
%h5
	Username:
	=@user.username